### PR TITLE
Remove empty temp dirs at plugin startup.

### LINKED ISSUE #34: S3 Output should clean up empty temp folders
https://github.com/logstash-plugins/logstash-integration-aws/issues/28 describes a situation where the s3 output cannot delete a temporary folder, due to the folder being non-empty. 

If we fail to delete the folder, we never attempt to delete again, raising a warning and moving on, leading to a proliferation of empty temp folders on systems that are prone to this issue (we believe that Windows boxes, in particular those running antivirus scans, are more prone to this issue than other systems).

The current cleanup implementation deliberately skips empty folders -

https://github.com/logstash-plugins/logstash-integration-aws/blob/main/lib/logstash/outputs/s3.rb#L399

and only cleans up folders containing partially completed upload files, and only if the `restore` option is selected in the configuration.

We should improve the cleanup process to also delete empty temporary folders.

### PR DESCRIPTION
**Pull request by mashhurs**
## Release notes
[rn:skip]

## What does this PR do?
For some environments, especially Windows OS, file scanning (such as antivirus enabled) tools hold temporarily created dirs' IO and a plugin cannot remove the temporarily dir after successfully uploading file to S3. Over time, there will be many empty temp dirs left under the `temporary_directory`.
This PR introduces a logic which, at the Logstash start up, plugin cleans up temporary dirs. 

## Why is it important/What is the impact to the user?
The users who are facing empty temp dirs left issues get benefit from this automation.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist
- [ ]

## Related issues
- Closes #34

### CODE REVIEW

**Comment by mashhurs** [comment]
🔴  CI is not relative and even re-run doesn't kick new run.

File: spec/outputs/s3_spec.rb [hunk 1]
```diff
@@ -229,4 +229,30 @@
...
     end
   end
+
+  context "remove empty dirs" do
+
+    before do
+      allow(File).to receive(:directory?).with('/path/to/bar-empty').and_return(true)
+      allow(File).to receive(:directory?).with('/path/to/foo/empty-dir').and_return(true)
+      allow(File).to receive(:directory?).with('/path/to/foo-file').and_return(true)
+      allow(File).to receive(:directory?).with('/path/to/foo-file/file.tmp').and_return(false)
```
Comment (robbavey) [inline spec/outputs/s3_spec.rb:239]: Missing `path/to/foo` from mocked case
```suggestion
      allow(File).to receive(:directory?).with('/path/to/foo-file/file.tmp').and_return(false)
      allow(File).to receive(:directory?).with('/path/to/foo').and_return(true)
```

File: spec/outputs/s3_spec.rb [hunk 2]
```diff
@@ -229,4 +229,30 @@
...
+
+      allow(Dir).to receive(:entries).with('/path/to/bar-empty').and_return([])
+      allow(Dir).to receive(:entries).with('/path/to/foo/empty-dir').and_return(%w(. ..))
+      allow(Dir).to receive(:entries).with('/path/to/foo-file').and_return(%w(/path/to/foo-file/file.tmp))
```
Comment (robbavey) [inline spec/outputs/s3_spec.rb:243]: Missing `path/to/foo` from mocked case

```suggestion
      allow(Dir).to receive(:entries).with('/path/to/foo-file').and_return(%w(/path/to/foo-file/file.tmp))
      allow(Dir).to receive(:entries).with('/path/to/foo').and_return(%w(. .. empty-dir))
```

File: spec/outputs/s3_spec.rb [hunk 3]
```diff
@@ -229,4 +229,30 @@
...
+
+    it "removes empty dirs" do
+      # Dir.glob() discovered files
+      files = %w(/path/to/bar-empty /path/to/foo/empty-dir /path/to/foo-file/file.tmp /path/to/foo-file)
+      removed_dirs = subject.send(:remove_empty_dirs, files)
+
+      expect(removed_dirs.include?('/path/to/bar-empty')).to be_truthy
+      expect(removed_dirs.include?('/path/to/foo/empty-dir')).to be_truthy
+      expect(removed_dirs.include?('/path/to/foo-file')).to be_falsey
+      expect(removed_dirs.include?('/path/to/foo-file/file.tmp')).to be_falsey
```
Comment (robbavey) [inline spec/outputs/s3_spec.rb:254]: Missing `path/to/foo`

```suggestion
      expect(removed_dirs.include?('/path/to/foo-file/file.tmp')).to be_falsey
      expect(removed_dirs.include?('/path/to/foo')).to be_falsey     
```

File: lib/logstash/outputs/s3.rb [hunk 4]
```diff
@@ -439,4 +440,19 @@ def get_under_recovery_files(files)
...
+  # Sorts explored files in desc order
+  # And proceeds bottom-up traversal remove operation if dir is empty
+  # Returns removed set to avoid duplicate Dir.glob process
+  def remove_empty_dirs(files)
+    removed_dirs = Set.new
+    files.sort { |x, y| y.length - x.length } # make sure to remove from leaf node
+         .select { |path| ::File.directory?(path) }
+         .select { |path| (Dir.entries(path) - %w[ . .. ]).empty? } # current and parent dirs escape
+         .each do |path|
+            FileUtils.rm_rf(path, :secure => true)
```
Comment (robbavey) [inline lib/logstash/outputs/s3.rb:453]: If the directory is empty, do we need to use `rm_rf` here, or can we use `rm_f`?

File: lib/logstash/outputs/s3.rb [hunk 5]
```diff
@@ -439,4 +440,19 @@ def get_under_recovery_files(files)
...
+            removed_dirs << path
```
Comment (robbavey) [inline lib/logstash/outputs/s3.rb:454]: Should we add a debug statement here that we are deleting a directory?

**Review by robbavey — CHANGES_REQUESTED** [review]

File: lib/logstash/outputs/s3.rb (hunk 5 above)
Comment (mashhurs) [reply lib/logstash/outputs/s3.rb:454]: Yup, good point.

File: lib/logstash/outputs/s3.rb (hunk 4 above)
Comment (mashhurs) [reply lib/logstash/outputs/s3.rb:453]: The intention was here to avoid handling `StandardError` cases, such as `IOError`.

Comment (robbavey) [reply lib/logstash/outputs/s3.rb:454]: I guess my question was more around the need to use the recursive (and destructive) form of `rm` rather than the `force` functionality. Would you expect that the recursive form is appropriate, and worth the risk of data loss in the event of a coding error?

Comment (mashhurs) [reply lib/logstash/outputs/s3.rb:454]: Ah got it. Yup, we don't need recursive operation here. We are starting to remove the leaf of the tree. Our operation itself is recursive, will change it to `FileUtils.rm_f`.

File: lib/logstash/outputs/s3.rb [hunk 6]
```diff
@@ -439,4 +440,20 @@ def get_under_recovery_files(files)
...
+  # And proceeds bottom-up traversal remove operation if dir is empty
+  # Returns removed set to avoid duplicate Dir.glob process
+  def remove_empty_dirs(files)
+    removed_dirs = Set.new
+    files.sort { |x, y| y.length - x.length } # make sure to remove from leaf node
+         .select { |path| ::File.directory?(path) }
+         .select { |path| (Dir.entries(path) - %w[ . .. ]).empty? } # current and parent dirs escape
+         .each do |path|
+            @logger.debug? && @logger.debug("Removing empty temporary file", :path => path)
+            FileUtils.rm_rf(path, :secure => true)
```
Comment (mashhurs) [inline lib/logstash/outputs/s3.rb:454]:
```suggestion
            FileUtils.rm_f(path)
```

**Review by robbavey — APPROVED** [review]
LGTM
